#!/usr/bin/env python3
"""design-sync buildCmd step 1 — inline the brand imagery the components need.

The components reference their imagery with absolute site paths
(`<img src="/img/logo.png">`), which only resolve when Astro is serving
public/. A design built from this system is served by claude.ai/design, not by
Astro, so every one of those paths 404s and the logo/partner wall render as
broken-image icons.

Rendered designs receive the styles.css @import closure plus the JS bundle and
nothing else, so the fix has to ride in the CSS: for each referenced asset we
emit an attribute-matched `content: url(<data-uri>)` rule, which replaces the
image on an <img> element. The hero's background <video> can't be replaced that
way, so its poster frame is attached as a background-image instead.

Images are downscaled to ~2x their rendered size first — inlining the originals
would put ~1.5MB of base64 into a stylesheet every design has to load.

Emits .design-sync/.cache/psb-assets.css (gitignored, regenerated every sync).
Requires Pillow.
"""

import base64
import io
import sys
from pathlib import Path

from PIL import Image

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
PUBLIC = ROOT / "public"
OUT = HERE / ".cache" / "psb-assets.css"

# (site path, max height px, max width px, jpeg quality or None to keep PNG)
# Heights are ~2x the size the component renders them at, for retina.
ASSETS = [
    ("/img/logo.png", 72, None, None),            # MktNav h30, MktFooter h32
    ("/img/pri.png", 96, None, None),             # Hero h44
    ("/img/pri-white.png", 96, None, None),
    ("/img/sustainalytics.png", 48, None, None),  # Hero h21
    ("/img/sustainalytics-white.png", 48, None, None),
    ("/img/real-impact-banner.jpg", None, 900, 72),
]
# Partners marquee: maxHeight 44, maxWidth 150 → 2x.
PARTNERS = [
    "morningstar-sustainalytics.jpg", "bluemark.png", "impact-evaluation-labs.png",
    "thrivent.png", "alterna.png", "nbh.png", "liberty-wellness.png", "kore-transfer.png",
]
for f in PARTNERS:
    ASSETS.append((f"/img/partners/{f}", 96, 320, 78 if f.endswith(".jpg") else None))

# The hero's <video> is decorative and aria-hidden. CSS can't swap a video
# source, so we paint its poster frame behind it — the hero then reads as
# intended instead of as a dark hole.
VIDEO_POSTER = ("/videos/banner-poster.jpg", 1000, 68)


def encode(src: Path, max_h, max_w, jpeg_q):
    im = Image.open(src)
    w, h = im.size
    scale = 1.0
    if max_h and h > max_h:
        scale = min(scale, max_h / h)
    if max_w and w > max_w:
        scale = min(scale, max_w / w)
    if scale < 1.0:
        im = im.resize((max(1, round(w * scale)), max(1, round(h * scale))), Image.LANCZOS)

    buf = io.BytesIO()
    if jpeg_q:
        im.convert("RGB").save(buf, "JPEG", quality=jpeg_q, optimize=True, progressive=True)
        mime = "image/jpeg"
    else:
        # Keep alpha — the partner marks and the logo are transparent PNGs.
        im.save(buf, "PNG", optimize=True)
        mime = "image/png"
    return mime, buf.getvalue(), im.size


def main():
    OUT.parent.mkdir(parents=True, exist_ok=True)
    rules = [
        "/* Generated by .design-sync/prepare-assets.py — do not edit.",
        "   Brand imagery inlined as data URIs: the components reference absolute",
        "   /img/ paths that do not resolve outside the Astro dev/prod server. */",
        "",
    ]
    total = 0
    missing = []

    for site_path, max_h, max_w, jpeg_q in ASSETS:
        src = PUBLIC / site_path.lstrip("/")
        if not src.exists():
            missing.append(site_path)
            continue
        mime, data, size = encode(src, max_h, max_w, jpeg_q)
        total += len(data)
        b64 = base64.b64encode(data).decode("ascii")
        rules.append(f'/* {site_path} → {size[0]}x{size[1]}, {len(data) // 1024}KB */')
        rules.append(f'img[src="{site_path}"] {{ content: url("data:{mime};base64,{b64}"); }}')
        rules.append("")

    poster_path, poster_w, poster_q = VIDEO_POSTER
    poster = PUBLIC / poster_path.lstrip("/")
    if poster.exists():
        mime, data, size = encode(poster, None, poster_w, poster_q)
        total += len(data)
        b64 = base64.b64encode(data).decode("ascii")
        rules.append(f'/* {poster_path} → {size[0]}x{size[1]}, {len(data) // 1024}KB (hero video fallback) */')
        rules.append(
            ".hero-video-wrap video {\n"
            f'  background-image: url("data:{mime};base64,{b64}");\n'
            "  background-size: cover;\n"
            "  background-position: center;\n"
            "}"
        )
        rules.append("")
    else:
        missing.append(poster_path)

    OUT.write_text("\n".join(rules), encoding="utf-8")
    print(
        f"prepare-assets: {len(ASSETS) + 1 - len(missing)} assets inlined, "
        f"{total // 1024}KB raw → {OUT.stat().st_size // 1024}KB css",
        file=sys.stderr,
    )
    if missing:
        print(f"prepare-assets: MISSING (left as broken refs): {', '.join(missing)}", file=sys.stderr)


if __name__ == "__main__":
    main()
